name: Build mcsm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- 1. Dependencies ---
      - name: Install Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-ninja

      # --- 2. Configure & Build (Linux & macOS) ---
      - name: CMake (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          # Set Big Sur target for Mac
          if [[ "${{ matrix.os }}" == macos* ]]; then
            export EXTRA_FLAGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0"
          fi
          
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_DEPS=0 $EXTRA_FLAGS
          cmake --build build --config Release

      # --- 3. Configure & Build (Windows MinGW) ---
      - name: CMake (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_DEPS=0 -DBUILD_STATIC_EXE=1
          cmake --build build --config Release

      # --- 4. Upload Result ---
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcsm-${{ matrix.os }}
          path: |
            build/mcsm
            build/mcsm.exe